spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23licLv31cWVNEzzKm
            client-secret: 72ff6364d773f5b5375dee66c1737adcf512fd10
          google:
            client-id: 92618875572-p4n7589u32aiv85216vn81d3uk6mlkke.apps.googleusercontent.com
            client-secret: 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